version: '3.8'

services:
   nginx:
      image: nginx
      ports:
         - '8080:80'
      volumes:
         - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      depends_on:
         - web-app

   mysql-db:
      image: mysql
      environment:
         MYSQL_ROOT_PASSWORD: root
         MYSQL_DATABASE: test_db
         MYSQL_USER: test
         MYSQL_PASSWORD: test
      ports:
         - '3307:3306'
      volumes:
         - mysql-data:/var/lib/mysql

   web-app:
      build: ./app
      depends_on:
         - mysql-db
      expose:
         - '3000'

volumes:
   mysql-data:
