version: '3.8'

services:
   nginx:
      image: nginx
      ports:
         - '8080:80' # Mapea puerto 80 del contenedor al 8080 del host
      volumes:
         - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      depends_on:
         - web-app

   mysql-db:
      image: mysql
      environment:
         MYSQL_ROOT_PASSWORD: root
         MYSQL_DATABASE: test_db
         MYSQL_USER: test
         MYSQL_PASSWORD: test
      ports:
         - '3307:3306' # Expone la base de datos en el puerto 3307 local
      volumes:
         - mysql-data:/var/lib/mysql

   web-app:
      build: ./app
      depends_on:
         - mysql-db
      expose:
         - '3000' # Expone el puerto 3000 para comunicación interna con nginx

volumes:
   mysql-data:
